name: scp files
on: [push]
jobs:

  testing:
    name: test scp action
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: appleboy/scp-action@v0.0.10
    - name: copy file via ssh password
      uses: ./
      env:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
      with:
        source: "/home/ubuntu/assignment/index.html"
        target: "/var/www/html"
        
