name: scp files
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "/home/ubuntu/assignment/index.html"
        target: "/var/www/html"
        run: scp -o StrictHostKeyChecking=no -r -p 2222 $source ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$target
