name: "Server Deployment"
on:
    push:
     branches:
       - main
jobs:
 deployment:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: Say Hello!
       run: echo "Hello there!"
     - name: Deploy code to Server
       env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
       run: echo $SSH_KEY > ssh-key && chmod 400 ssh-key && ssh -vvv -i ssh-key -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_PORT }} sshpass -p ${{ secrets.SSH_PASSWORD }} "cd ${{ secrets.WORK_DIR }} && GIT_SSH_COMMAND='ssh -i /home/ubuntu/.ssh/ssh-key' git pull origin main"
