name: "Server Deployment"
on:
    push:
     branches:
       - main
jobs:
 deployment:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: Say Hello!
       run: echo "Hello there!"
    # - name: executing remote ssh commands using password
    #   uses: appleboy/ssh-action@master
    #   with:
    #      host: ${{ secrets.SSH_HOST }}
    #      password: ${{ secrets.SSH_PASSWORD }}
    #      username: ${{ secrets.SSH_USERNAME }}
    #      port: ${{ secrets.SSH_PORT }}
     - name: Deploy code to Server
       env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
       run: echo $SSH_KEY > ssh-key && chmod 600 ssh-key && ssh -vvv ssh-key -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} sshpass -p ${{ secrets.SSH_PASSWORD }} "cd ${{ secrets.WORK_DIR }} && GIT_SSH_COMMAND='ssh -i /home/ubuntu/.ssh/ssh-key' git pull origin main"
