name: scp files
on: [push]
jobs:
 build:
    name: Build
    runs-on: ubuntu-latest
 needs: build
   steps:
      - uses: actions/checkout@v2
      - run: mkdir ~/distfiles/
      - uses: actions/download-artifact@master
        with:
          name: distfiles
          path: ~/distfiles/
      - uses: actions/checkout@master
      - name: copy file via ssh password
   #     uses: appleboy/scp-action@master
      -  uses: appleboy/scp-action@v0.0.10
 #     env:
 #       host: ${{ secrets.SSH_HOST }}
 #       username: ${{ secrets.SSH_USERNAME }}
 #       key: ${{ secrets.SSH_PRIVATE_KEY }}
 #       passphrase: ${{ secrets.SSH_PASSWORD }}
 #       port: ${{ secrets.SSH_PORT }}
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          rm: true
          source: "/home/ubuntu/assignment/index.html"
          target: "/var/www/html"
       #   run: scp -o StrictHostKeyChecking=no -r -p 2222 $source ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$target
          strip_components: 1
