name: Deploy on server
on:
  push:
   branches:
       — main
jobs:
 deploy:
     name: Deploy branch master
     runs-on: ubuntu-latest
     steps:
     - name: Checkout and restart the server
       uses: appleboy/ssh-action@main
       with:
           host: ${{ secrets.SSH_HOST }}
           username: ${{ secrets.SSH_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
     - name: connect and pull
       run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && exit"
     - name: cleanup
       run: rm -rf ~/.ssh
    #       script: |
     #       cd /home/ubuntu/polls/polls
      #      git checkout — *
       #     git checkout master
       #     git pull origin master
  #          sudo kill $(ps aux | grep gunicorn | grep -v grep | awk ‘{print $2}’)
   #         sudo /home/ubuntu/polls/.venv/bin/gunicorn — daemon —  workers=4 mysite.wsgi:application -b 0.0.0.0:80
