name: scp files
on: [push]
jobs:

  testing:
    name: test scp action
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: copy file via ssh password
      uses: ./
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "/home/ubuntu/assignment/index.html"
        target: "/var/www/html"
        
