name: deploy svr-prod

on:
  release:
    types: [main]

jobs:
  # Test

  # Build

  # Bump version
  # After successful test and build, then bump version before deployment.
  version-bump:
    runs-on: ubuntu-latest
    name: Bump version
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: svr-prod
      - name: Update version and commit
        run: |
          date > code/latest-release.txt
          targetConfigFile="config/version.txt"
          git fetch --prune --unshallow
          oldVersion=$(awk '{print $6}' $targetConfigFile)
          newVersion="'"$(git describe --tags --abbrev=0 --always)"'"
          echo "Bumping..."
          echo " Old Version = "$oldVersion
          echo " New Version = "$newVersion
          awk '{$6 = "'$newVersion'"; print}' $targetConfigFile > $targetConfigFile".tmp" \
          && mv $targetConfigFile".tmp" $targetConfigFile
          echo "Done."
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Robot Commit: Auto version bump on svr-prod deploy"
          git push

  # Deploy
#  deploy:
#    needs: version-bump
#    runs-on: ubuntu-22.04
#      steps:
#        - name: Install SSH Key
#          uses: shimataro/ssh-key-action@v2.1.0
#          with:
#          key: $
#          known_hosts: $
#        - name: Execute deployment Script
#    	    run: ssh username@myserver.svr-prod.com && "cd application-prod-test/$-Deploy && ./deploy.sh"
#          run: ssh username@myserver.svr-prod.com && "cd application-prod-live/$-Deploy && ./deploy.sh"
