name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies (if needed)
      run: |
        # Add any commands to install dependencies if needed

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # Only deploy if index.html has changed
        if [ -n "$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'index.html')" ]; then
          # Replace <EC2_USER>, <EC2_HOST>, and /path/to/remote/directory with appropriate values
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} index.html ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }} -p {{ secrets.SSH_PORT }} 
          echo "index.html not changed. Skipping deployment."
        fi
