name: "Server Deployment"
on:
    push:
     branches:
       - main
jobs:
 deployment:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: Say Hello!
       run: echo "Hello there!"
     - name: executing remote ssh commands using password
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.SERVER_HOST }}
          password: ${{ secrets.SERVER_PASSWORD }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: 22
     - name: Deploy code to Server
       env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
       run: echo $SSH_KEY > ssh-key && chmod 600 ssh-key && ssh -vvv -i ssh-key -o StrictHostKeyChecking=no ubuntu@15.206.160.20 -p 2222 sshpass -p 'Exemplifi123@#$' "cd /var/www/html && GIT_SSH_COMMAND='ssh -i /home/ubuntu/.ssh/ssh-key' git pull origin main"
