name: "Server Deployment"
on:
    push:
     branches:
       - main
jobs:
 deployment:
     runs-on: self-hosted
     steps:
     - uses: actions/checkout@v2
     - name: Say Hello!
       run: echo "Hello there!"
#     - name: Run sshpass commands
#       uses: matheusvanzan/sshpass-action@v2
     - name: Deploy code to Server
       env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }} 
       run: "cd /home/ubuntu && git pull origin main && cp /home/ubuntu/html/index.html /var/www/html"
     #  run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && exit"
